  <?php echo $this->flashSession->output(); 
 
  $username='';
  $password='';
  $rememberMe='';
 
  if($this->cookies->has("username") && $this->cookies->has("password") )
  {
      $username=$this->cookies->get("username");
      $password=$this->cookies->get("password");
      $rememberMe='checked';
  }
?>
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">
  <form action="" method="post">
    <br>
    <div class="form-group">
    <center>
    <label><hr><b>Login</b><hr></label>
    </center>
      <label>Email address</label>
      <input type="email" name="email" class="form-control" id="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" placeholder="Enter email" value="<?php if(isset($username))echo $username; ?>" required>
    </div>
    <div class="form-group">
      <label>Password</label>
      <input type="password" name="password" class="form-control" id="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required>
     
    </div>
    <div class="form-check">
      <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>>
 
      <label class="form-check-label" for="rememberMe">Remember me</label>
    </div>
    <button type="submit" class="btn btn-info">Submit</button>
   
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
   
  </form>
  </div>
    <div class="col-sm">     
    </div>
  </div>
