<div class="row">
  <div class="col-sm">
  </div>
  <div class="col-sm">
    <form action="" method="post" enctype="multipart/form-data">
      <center>
        <div class="form-group">
          <label>Developed by</label>
        </div>
        <div class="form-group">
          <img src = "<?php echo $this->url->getBaseUri(); ?>public/img/dev.jpg" width="200px" class="img-thumbnail">
        </div>
        <div class="form-group">
          <hr>Wanarut  Boonyung</hr>
        </div>
        <div class="form-group">
          <hr>590610656</hr>
        </div>
        <br>
        <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
      </center>
    </form>
  </div>
  <div class="col-sm">
  </div>
</div>