<div class="row">
  <div class="col-sm">
  </div>
  <div class="col-sm">
    <form action="" method="post" enctype="multipart/form-data">
      <center>
        <div class="form-group">
          <label>Contact Us</label>
        </div>
        <div class="form-group">
          <b>Phone : </b>
          <a href="tel:0823854726"><b>082-385-4726</b></a>
        </div>
        <div class="form-group">
          <hr>Wanarut</hr>
        </div>
        <br>
        <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
        <br><br><br><br>
      </center>
    </form>
  </div>
  <div class="col-sm">
  </div>
</div>